const foods=[
  {id:1,name:"Chicken Breast",calories:165,protein:31,carbs:0,fat:4},
  {id:2,name:"Jasmine Rice",calories:205,protein:4,carbs:45,fat:0},
  {id:3,name:"Greek Yogurt",calories:130,protein:20,carbs:8,fat:0},
  {id:4,name:"Banana",calories:105,protein:1,carbs:27,fat:0},
  {id:5,name:"Whole Eggs",calories:155,protein:13,carbs:1,fat:11},
  {id:6,name:"Salmon",calories:208,protein:20,carbs:0,fat:13},
  {id:7,name:"Oats",calories:154,protein:6,carbs:27,fat:3},
  {id:8,name:"Whey Protein",calories:120,protein:24,carbs:3,fat:1},
  {id:9,name:"Apple",calories:95,protein:0,carbs:25,fat:0},
  {id:10,name:"Almonds",calories:164,protein:6,carbs:6,fat:14},
  {id:11,name:"Brown Rice",calories:216,protein:5,carbs:45,fat:2},
  {id:12,name:"Sweet Potato",calories:112,protein:2,carbs:26,fat:0},
  {id:13,name:"Peanut Butter",calories:188,protein:8,carbs:6,fat:16},
  {id:14,name:"Avocado",calories:234,protein:3,carbs:12,fat:21},
  {id:15,name:"Ground Beef (90/10)",calories:199,protein:27,carbs:0,fat:10}
];
const exerciseLibrary=[
    {id:"bench-press",name:"Bench Press",aliases:"barbell bench chest press",muscle:"Chest",secondary:"Triceps, Front delts",equipment:"Barbell",level:"Intermediate",pattern:"Horizontal Push",mechanics:"Compound",defaultSets:4,defaultReps:"5-8",defaultRest:150,tempo:"3-1-1",progression:"Add 5 lb when every set reaches the top of the rep range with clean bar speed.",steps:["Set eyes under the bar and plant feet hard.","Pin shoulder blades back and down.","Lower to lower chest with wrists stacked.","Press up and slightly back while keeping hips down."],cues:["Break the bar","Chest tall","Leg drive"],mistakes:["Bouncing reps","Loose shoulders","Elbows flared"],targets:["Pecs","Triceps","Anterior delts"],animation:"push"},
    {id:"back-squat",name:"Back Squat",aliases:"barbell squat",muscle:"Legs",secondary:"Glutes, Core",equipment:"Barbell",level:"Intermediate",pattern:"Squat",mechanics:"Compound",defaultSets:5,defaultReps:"3-6",defaultRest:180,tempo:"3-1-1",progression:"Add load when depth, brace and knee tracking stay consistent.",steps:["Brace ribs down and pull elbows under the bar.","Sit between hips while knees track over toes.","Reach controlled depth without spinal collapse.","Drive the floor away and keep chest rising."],cues:["Tripod foot","Knees out","Brace first"],mistakes:["Heels lifting","Knees caving","Good-morning reps"],targets:["Quads","Glutes","Adductors"],animation:"squat"},
    {id:"deadlift",name:"Deadlift",aliases:"conventional deadlift",muscle:"Back",secondary:"Glutes, Hamstrings",equipment:"Barbell",level:"Advanced",pattern:"Hinge",mechanics:"Compound",defaultSets:4,defaultReps:"3-5",defaultRest:210,tempo:"2-1-1",progression:"Add 5-10 lb when the bar stays close and back angle remains stable.",steps:["Place mid-foot under bar.","Hinge to grip and pull slack out.","Push the floor while bar stays against legs.","Lock out with glutes, not by leaning back."],cues:["Armpits tight","Push floor","Bar close"],mistakes:["Jerking the bar","Rounded back","Overextended lockout"],targets:["Glutes","Hamstrings","Lats"],animation:"hinge"},
    {id:"pull-up",name:"Pull Up",aliases:"chin up weighted pullup",muscle:"Back",secondary:"Biceps",equipment:"Bodyweight",level:"Intermediate",pattern:"Vertical Pull",mechanics:"Compound",defaultSets:4,defaultReps:"6-10",defaultRest:120,tempo:"2-1-2",progression:"Add reps first, then external load after clean sets of 10.",steps:["Start from controlled hang.","Pull elbows toward ribs.","Pause near top without neck reach.","Lower under control to full reach."],cues:["Chest to bar","Elbows down","Quiet legs"],mistakes:["Half reps","Shrugging","Uncontrolled drop"],targets:["Lats","Biceps","Lower traps"],animation:"pull"},
    {id:"overhead-press",name:"Overhead Press",aliases:"military press",muscle:"Shoulders",secondary:"Triceps, Core",equipment:"Barbell",level:"Intermediate",pattern:"Vertical Push",mechanics:"Compound",defaultSets:4,defaultReps:"5-8",defaultRest:150,tempo:"2-1-1",progression:"Add small jumps after all reps stay stacked over mid-foot.",steps:["Grip just outside shoulders and squeeze glutes.","Brace and press bar straight up.","Move head through as bar clears forehead.","Lower to upper chest under control."],cues:["Ribs down","Bar close","Head through"],mistakes:["Overarching","Bent wrists","Soft core"],targets:["Delts","Triceps","Upper chest"],animation:"press"},
    {id:"barbell-row",name:"Barbell Row",aliases:"bent over row",muscle:"Back",secondary:"Biceps, Rear delts",equipment:"Barbell",level:"Intermediate",pattern:"Horizontal Pull",mechanics:"Compound",defaultSets:4,defaultReps:"6-10",defaultRest:120,tempo:"2-1-2",progression:"Increase load only when torso angle and pause stay stable.",steps:["Hinge and brace.","Pull bar to lower ribs.","Pause while squeezing shoulder blades.","Lower until arms are long."],cues:["Still torso","Elbows to pockets","Own the pause"],mistakes:["Standing up","Yanking","Neck cranking"],targets:["Lats","Rhomboids","Rear delts"],animation:"pull"},
    {id:"incline-db-press",name:"Incline Dumbbell Press",aliases:"incline press",muscle:"Chest",secondary:"Shoulders, Triceps",equipment:"Dumbbell",level:"Beginner",pattern:"Incline Push",mechanics:"Compound",defaultSets:3,defaultReps:"8-12",defaultRest:90,tempo:"3-0-1",progression:"Add reps to all sets before increasing dumbbells.",steps:["Set bench at 25-35 degrees.","Start over upper chest with shoulders packed.","Lower until elbows sit slightly below chest.","Press up and inward smoothly."],cues:["Low incline","Shoulders packed","Smooth arc"],mistakes:["Bench too steep","Short range","Flaring"],targets:["Upper pecs","Front delts","Triceps"],animation:"push"},
    {id:"romanian-deadlift",name:"Romanian Deadlift",aliases:"RDL",muscle:"Legs",secondary:"Hamstrings, Glutes",equipment:"Barbell",level:"Intermediate",pattern:"Hinge",mechanics:"Compound",defaultSets:4,defaultReps:"6-10",defaultRest:150,tempo:"3-1-1",progression:"Progress load when hamstring tension is high and spine remains neutral.",steps:["Start tall with soft knees.","Push hips back while bar slides down thighs.","Stop when hamstrings limit range.","Drive hips forward and squeeze glutes."],cues:["Hips back","Long spine","Shins vertical"],mistakes:["Squatting it","Bar drifting","Chasing floor"],targets:["Hamstrings","Glutes","Erectors"],animation:"hinge"},
    {id:"leg-press",name:"Leg Press",aliases:"machine leg press",muscle:"Legs",secondary:"Glutes",equipment:"Machine",level:"Beginner",pattern:"Squat",mechanics:"Compound",defaultSets:4,defaultReps:"10-15",defaultRest:105,tempo:"3-1-1",progression:"Add reps while depth stays controlled and hips stay on pad.",steps:["Set feet shoulder-width.","Unlock handles and lower sled under control.","Stop before pelvis rolls away.","Press through mid-foot without hard knee lock."],cues:["Control depth","Knees track toes","No hard lockout"],mistakes:["Hands on knees","Tiny reps","Butt lifting"],targets:["Quads","Glutes","Adductors"],animation:"squat"},
    {id:"lat-pulldown",name:"Lat Pulldown",aliases:"pulldown",muscle:"Back",secondary:"Biceps",equipment:"Cable",level:"Beginner",pattern:"Vertical Pull",mechanics:"Compound",defaultSets:3,defaultReps:"10-12",defaultRest:90,tempo:"2-1-2",progression:"Add load when chest stays tall and reps finish below chin.",steps:["Grip slightly wider than shoulders.","Lean back slightly with ribs controlled.","Drive elbows down to upper chest.","Return slowly until lats lengthen."],cues:["Elbows to ribs","Chest tall","Slow return"],mistakes:["Behind-neck reps","Momentum lean","Shrugging"],targets:["Lats","Biceps","Lower traps"],animation:"pull"},
    {id:"plank",name:"Plank",aliases:"front plank",muscle:"Core",secondary:"Shoulders, Glutes",equipment:"Bodyweight",level:"Beginner",pattern:"Anti-Extension",mechanics:"Isometric",defaultSets:3,defaultReps:"30-60 sec",defaultRest:60,tempo:"Hold",progression:"Add time, reach variations, or weight once posture is perfect.",steps:["Set elbows under shoulders.","Squeeze glutes and tuck ribs.","Push floor away and breathe behind brace.","Stop when position changes."],cues:["Ribs down","Glutes on","Long neck"],mistakes:["Sagging hips","Holding breath","Head dropped"],targets:["Abs","Transverse abs","Glutes"],animation:"plank"},
    {id:"lateral-raise",name:"Lateral Raise",aliases:"side raise",muscle:"Shoulders",secondary:"Upper traps",equipment:"Dumbbell",level:"Beginner",pattern:"Shoulder Abduction",mechanics:"Isolation",defaultSets:4,defaultReps:"12-20",defaultRest:60,tempo:"2-1-2",progression:"Progress slowly with clean control and no torso swing.",steps:["Hold light dumbbells slightly in front.","Raise out and slightly forward to shoulder height.","Pause with soft elbows.","Lower slowly without losing tension."],cues:["Lead with elbows","Soft neck","No swing"],mistakes:["Too heavy","Shrugging","Momentum"],targets:["Side delts","Supraspinatus"],animation:"raise"}
];
const exercises=exerciseLibrary.map(e=>e.name);
const workoutTemplates=[
  {name:"Push / Pull / Legs",goal:"Balanced strength + hypertrophy",days:6,exercises:["Bench Press","Overhead Press","Barbell Row","Pull Up","Back Squat","Romanian Deadlift"]},
  {name:"Upper / Lower Strength",goal:"Four day power split",days:4,exercises:["Bench Press","Barbell Row","Back Squat","Deadlift"]},
  {name:"Full Body Foundation",goal:"Beginner-friendly three day plan",days:3,exercises:["Back Squat","Incline Dumbbell Press","Lat Pulldown","Romanian Deadlift","Plank"]},
  {name:"Hypertrophy Pump",goal:"Higher rep bodybuilding focus",days:5,exercises:["Incline Dumbbell Press","Lat Pulldown","Leg Press","Lateral Raise"]}
];
